version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 99
  target-branch: dev
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.3.3
    - 8.4.1
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: "@nuxtjs/tailwindcss"
    versions:
    - 3.4.2
    - 3.4.3
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: nuxt
    versions:
    - 2.14.12
    - 2.15.0
    - 2.15.1
    - 2.15.2
    - 2.15.3
  - dependency-name: "@nuxtjs/sentry"
    versions:
    - 5.0.0
    - 5.0.1
    - 5.0.2
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: eslint-config-prettier
    versions:
    - 6.15.0
  - dependency-name: eslint
    versions:
    - 7.7.0
  - dependency-name: "@nuxtjs/eslint-config"
    versions:
    - 3.1.0
  - dependency-name: "@nuxtjs/imagemin"
    versions:
    - 0.2.0
